export type Options = {
  filename?: string,
  runToStage?: string | null,
  literate?: boolean,
  disableSuggestionComment?: boolean,
  useOptionalChaining?: boolean,
  noArrayIncludes?: boolean,
  useJSModules?: boolean,
  looseJSModules?: boolean,
  safeImportFunctionIdentifiers?: Array<string>,
  preferLet?: boolean,
  looseDefaultParams?: boolean,
  looseForExpressions?: boolean,
  looseForOf?: boolean,
  looseIncludes?: boolean,
  looseComparisonNegation?: boolean,
  disableBabelConstructorWorkaround?: boolean,
  disallowInvalidConstructors?: boolean,
};

export const DEFAULT_OPTIONS: Options = {
  filename: 'input.coffee',
  runToStage: null,
  literate: false,
  disableSuggestionComment: false,
  useOptionalChaining: false,
  noArrayIncludes: false,
  useJSModules: false,
  looseJSModules: false,
  safeImportFunctionIdentifiers: [],
  preferLet: false,
  looseDefaultParams: false,
  looseForExpressions: false,
  looseForOf: false,
  looseIncludes: false,
  looseComparisonNegation: false,
  disableBabelConstructorWorkaround: false,
  disallowInvalidConstructors: false,
};
